version: "3.0"
services:
  api:
    container_name: api-container
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_HOST=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - ./data:/usr/src/app/data

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    networks:
      - es-net
    ports:
      - 9200:9200
    command: >
      bash -c '
      elasticsearch-plugin install analysis-icu;
      elasticsearch-plugin install analysis-kuromoji;
      chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/plugins/;
      /usr/local/bin/docker-entrypoint.sh
      '
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
networks:
  es-net:
    driver: bridge
